### PR TITLE
qpp: unit test (QUnit) generator - initial revision

### PR DESCRIPTION
**Pull request by pvanek**
@davidnich please review and suggest what is needed

Current result is set of files which can be taken as a base for real unit test. Test maintainer then must just implement real tests for each function/class

The TODO: to be able to get list of addTestCase() calls in advance.

```
#!/usr/bin/env qore
# -*- mode: qore; indent-tabs-mode: nil -*-

%new-style
%enable-all-warnings
%require-types
%strict-args

%requires ../../../qlib/QUnit.qm

%exec-class Main

class Main inherits QUnit::Test {

    constructor() : Test("Main", "1.0", \ARGV) {

        # addTestCase("foobar", \testFoobar());

        # Return for compatibility with test harness that checks return value.
        set_return_value(main());
    }

    # Qore class Qore::RangeIterator
    private test_Qore_RangeIterator() {
        # nothing RangeIterator::constructor(int start, int stop, int step = 1, any val){}
        # nothing RangeIterator::constructor(int stop, any val){}
        # nothing RangeIterator::copy(){}
        # any RangeIterator::getValue(){}
        # bool RangeIterator::next(){}
        # nothing RangeIterator::reset(){}
        # bool RangeIterator::valid(){}
    }

    # QC_RangeIterator.qpp: 284
    private test_QC_RangeIterator_qpp_284() {
        # RangeIterator xrange(int start, int stop, int step = 1, any val) {}
        # RangeIterator xrange(int stop, any val) {}
    }

} # class Main 
```

### CODE REVIEW

**Comment by davidnich** [comment]
@pvanek it looks good - I would say just have qpp add real `addTestCase()` calls for each test case - the qtest script then should run by default (but have no assertions)

also ideally the qtest script should be created with the executable bit set

**Comment by pavelkveton** [comment]
I don't fully see what pieces of code we cover with the automaticly generated test cases (classes, methods?, global function, anything else). But it's my problem.

I'd say if we already automaticly generate test cases, then enable them and put assert(false) into them by default and let the developer decide to comment it out or (better) write a proper function.

**Comment by pvanek** [comment]
Coverage: functions and class methods.

The idea is to provide a "skel" for unit test for anything callable in qore - real person then should make it really done. I see some one week all-company code sprint to cover 100% of qore. I assume than all new development is/will be test covered. So maybe it can be onetime run = no real pull request.

Anyway, i will update it to fit your comments

**Comment by pvanek** [comment]
OK, your suggestions have been implemented. I hope that chmod() works on windows too.

This is how output looks now (with executable priv for owner):

```
#!/usr/bin/env qore
# -*- mode: qore; indent-tabs-mode: nil -*-

%new-style
%enable-all-warnings
%require-types
%strict-args

%requires ../../../qlib/QUnit.qm

%exec-class Main

class Main inherits QUnit::Test {

    constructor() : Test("Main", "1.0", \ARGV) {

        addTestCase("test_Qore_RangeIterator", \test_Qore_RangeIterator());
        addTestCase("test_QC_RangeIterator_qpp_284", \test_QC_RangeIterator_qpp_284());

        # Return for compatibility with test harness that checks return value.
        set_return_value(main());
    }

    # Qore class Qore::RangeIterator
    private test_Qore_RangeIterator() {
        # nothing RangeIterator::constructor(int start, int stop, int step = 1, any val){}
        # nothing RangeIterator::constructor(int stop, any val){}
        # nothing RangeIterator::copy(){}
        # any RangeIterator::getValue(){}
        # bool RangeIterator::next(){}
        # nothing RangeIterator::reset(){}
        # bool RangeIterator::valid(){}
        assertEq(True, False, "assertion placeholder; the real test needs to be implemented");
    }

    # QC_RangeIterator.qpp: 284
    private test_QC_RangeIterator_qpp_284() {
        # RangeIterator xrange(int start, int stop, int step = 1, any val) {}
        # RangeIterator xrange(int stop, any val) {}
        assertEq(True, False, "assertion placeholder; the real test needs to be implemented");
    }

} # class Main 
```

**Comment by davidnich** [comment]
+1 for me - very good - @omusil24 please review from a c++ perspective and merge if it's ok with you too

**Pull request merged**
