### PR TITLE
refs #3395 fixed a crash deserializing invalid integer data

### PR DESCRIPTION
**Pull request by davidnich**

### CODE REVIEW

**Comment by sejvlond** [comment]
@davidnich I've squashed the commits so that there are no 'fix typo in comment' and updated over develop to get latest changes (conflict in rel notes), can you please check, it's fine and I'll merge it

**Comment by sejvlond** [comment]
@davidnich will you have time to check the CI problem? thx

**Comment by davidnich** [comment]
the pipeline passed, but github is not updated - not sure what's wrong: https://git.qoretechnologies.com/mirror/qore/pipelines/2593/builds

**Comment by davidnich** [comment]
@sejvlond the changes are fine; we may need to disable the CI check and merge; I suspect that the problems are related to the gitlab reinstallation

**Comment by sejvlond** [comment]
@omusil24 can you please check and maybe run the pipeline again? thx

**Pull request merged**
