### PR TITLE
refs #2030 do not evaluate base class constructor argument twice; only…

### PR DESCRIPTION
**Pull request by davidnich**
… evalute once when the constructor is executed; in this case for user constructors also handle argv lvar instantiation, added test + relnote

### CODE REVIEW

**Comment by pavelkveton** [comment]
@davidnich isn't this issue critical also for 0.8.11.x?

**Review by omusil24 — APPROVED** [review]

**Comment by omusil24** [comment]
Unless it's urgent, I will merge this after merging the typed hashes PR.

**Comment by davidnich** [comment]
@omusil24 no problem; I've written some additional tests, and I think there are some issues; I will reassign it to you when it's ready with the new fixes

**Comment by davidnich** [comment]
@omusil24 now it's OK

**Review by omusil24 — APPROVED** [review]

**Pull request merged**
