### PR TITLE
refs #3047 added missing error handling with separated modules

### PR DESCRIPTION
**Pull request by davidnich**
@petrycta let's discuss this if the need for this is not clear

### CODE REVIEW

**Review by petrycta — COMMENTED** [review]
when exactly should I check xsink? After every time I transfer it?

**Comment by davidnich** [comment]
> when exactly should I check xsink? After every time I transfer it?

@petrycta every time you make a call passing an `ExceptionSink` argument, an exception could be thrown, so in that case you would need to manually check for an exception

**Comment by petrycta** [comment]
@davidnich ok, should it be checked also here?:
QoreUserModuleDefContextHelper qmd(feature, mpgm, xsink);
and
userModule->getProgram()->parsePending(moduleCode.c_str(), feature, &xsink, &xsink, QP_WARN_MODULES);
and 
QoreDir moduleDir(&xsink, QCS_DEFAULT, path.c_str());

**Comment by davidnich** [comment]
> @davidnich ok, should it be checked also here?:
> QoreUserModuleDefContextHelper qmd(feature, mpgm, xsink);
> and
> userModule->getProgram()->parsePending(moduleCode.c_str(), feature, &xsink, &xsink, QP_WARN_MODULES);
> and
> QoreDir moduleDir(&xsink, QCS_DEFAULT, path.c_str());

@petrycta if an exception can happen and you need to modify the program flow after the call depending on a possible exception then yes

**Comment by petrycta** [comment]
ok, then I think it should be checked also here:
line 898: userModule->getProgram()->parsePending(moduleCode.c_str(), feature, &xsink, &xsink, QP_WARN_MODULES);

**Comment by davidnich** [comment]
@petrycta looks good!

**Pull request merged**
