### PR TITLE
refs #2826 Statements don't always issue a parse error when having no meaning as a whole

### PR DESCRIPTION
**Pull request by martin-zemek**

### CODE REVIEW

**Review by davidnich — COMMENTED** [review]
why can't `PF_BACKGROUND` be used in place of the new `PF_BACKGROUND_CALL_RETURN_VALUE_IGNORED `?

**Review by davidnich — CHANGES_REQUESTED** [review]
looks good, except for the issue with backwards compatibility.  We could break existing working code by making statements like `1 + printf("1");` an error - this worked before.

It's fine for me if it's an error by default, but then we would need a compatibility flag to change this to a warning - something like `%compat-allow-statement-no-effect` (or something similar if you can find something shorter & better).   We have to pay close attention to backwards compatibility in fact.

**Comment by davidnich** [comment]
@martin-zemek this breaks working code - ex:
```
nhandled QORE System exception thrown in TID 1 at 2018-06-27 10:57:58.562775 Wed +02:00 (CEST) at misc.ql:1282
RETURN-VALUE-IGNORED: call to function encrypt() does not have any side effects except that it may throw an exception and the return value is ignored; to disable this warning, use '%disable-warning return-value-ignored' in your code
```

here is the code - explicitly testing for an exception:
```
            # validate keys
            try {
                encrypt(CRYPTO_ALG_AES_256, "x", sd_key);
            }
            catch (hash<ExceptionInfo> ex) {
                throw "QORUS-ENCRYPTION-ERROR", sprintf("System option \"sensitive-data-key\" = %y, however the key is not usable: %s: %s; please correct the key file to contain 32 bytes of key data and try again", dfn, ex.err, ex.desc);
            }
```

**Comment by martin-zemek** [comment]
It changes the behavior of existing code only in that there is the extra warning of `RETURN-VALUE-IGNORED`. As to handling exceptions, it behaves exactly the same as before (if the example code did not re-throw another exception the warning would be the only message).

The warning can be suppressed by `%disable-warning return-value-ignored` - similarly as the new parse option `%allow-statement-no-effect` fixes breaking of existing code like`1 + printf("1")`;  (earlier in this discussion).

(But I wouldn't mind removing the `RETURN-VALUE-IGNORED` warning from calls to functions that only may throw an exception and leave it only for calls that don't have any effect at all, as it was before - it's still open for a discussion.)

**Comment by davidnich** [comment]
@martin-zemek I merged develop in here, but I believe that I broke something, please check it

**Comment by martin-zemek** [comment]
My proposal is to implement a new operator called `ignore` that

- accepts anything
- does nothing
- has effect

The above example will look as follows:
```
try {
    ignore encrypt(CRYPTO_ALG_AES_256, "x", sd_key);
} ...
```

**Comment by davidnich** [comment]
@martin-zemek I would rather have a function called `nothing ignore(...)` so that we don't introduce a new keyword into the language - i.e.:

```
try {
    ignore(encrypt(...));
} ...
```

**Comment by sejvlond** [comment]
both (`ignore xxx` and `ignore(xxx())`) invoke me that the call is ignored, not the returned value.
I've talked with @pvanek and he likes the `_` special variable the most, either
`_ = encrypt`
or
`auto _ = encrypt`

but both would be a 'hack' in terms that this variable has to be immediately dereferenced, multiple assignment to it wouldn't lead to redefinition of the variable and the `_` cannot be used otherwise then assigning to it, something like /dev/null :)

Also, `_` is a valid variable name, so it can be already used in some code (I've already used it in one client's code)
`src/032-.....qtest:        foreach auto _ in (1..trans_amount) {`

**Comment by martin-zemek** [comment]
No, `ignore(f())` does not make the impression that the call is ignored, `ignore(x)` ignores its argument `x`, may `x` be whatever.

**Comment by davidnich** [comment]
@martin-zemek @sejvlond you could also call it `ignore_arg(...)` or `ignore_exp(...)` to avoid ambiguity.  Also using `_` as an automatically-ignored var ala Go would potentially cause compatibility problems, as `_` is currently a valid variable name

**Comment by martin-zemek** [comment]
Yes, function `ignore()` will be better than operator `ignore`. 
And to implement the  function `ignore()` is in fact trivial.

**Comment by davidnich** [comment]
or maybe `ignore_rv()` or `eval_ignore()` or something else could be better....

**Comment by sejvlond** [comment]
> potentially cause compatibility problems, as _ is currently a valid variable name

well, `ignore` is a valid function name also, maybe more often used than `_` I think...

**Comment by martin-zemek** [comment]
To me the form of `ignore(x)` looks the most natural since it clearly expresses its meaning.

**Comment by sejvlond** [comment]
@martin-zemek and you would put  `sub ignore(auto arg)` to `Qore::` namespace?

**Comment by davidnich** [comment]
> well, `ignore` is a valid function name also, maybe more often used than `_` I think...

`ignore()` would be `Qore::ignore()` so it would be used after any `ignore()` function created in the root namespace, so if there were a `sub ignore() {}` already defined, it would be used by default.

**Comment by sejvlond** [comment]
`_` is a valid variable name, but `@` is not and it looks more like flushing the value to toilette :) so

`@ = encrypt` (without auto/type)

**Comment by sejvlond** [comment]
> function created in the root namespace ...  it would be used by default.

yes, but something like `App::Helper::ignore` would be now called, and after this change it won't right, just saying, there can be compatibility issues as well I think

**Comment by martin-zemek** [comment]
It would be a builtin function implemented in the file `ql_misc.qpp` as
```
nothing ignore(auto value) {
}
```
(with no flags).

**Comment by geckon** [comment]
I quite like the idea of using a special variable for this. If `_` can't be used because of compatibility, maybe the `@` could be used instead as Ondra suggested.

`ignore_*()` function could be used as well but I found it a bit less intuitive and the compatibility issue is there as well (even though smaller).

**Comment by davidnich** [comment]
@sejvlond the idea with `@` seems good to me and would not introduce any parser issues, what do you think?  @martin-zemek what do you think about that one?

**Comment by omusil24** [comment]
> Also, `_` is a valid variable name, so it can be already used in some code (I've already used it in one client's code)
`src/032-.....qtest:        foreach auto _ in (1..trans_amount) {`

@sejvlond just out of curiosity, why would you use a name like that instead of something more standard like `i` or `x`, or even something like `index`?

Anyway, if you go with the idea of adding `@`, then astparser would have to be modified as well.

**Comment by sejvlond** [comment]
@omusil24: 
> @sejvlond just out of curiosity, why would you use a name like that instead of something more standard like i or x, or even something like index?

because I didn't care about the `index`, I just wanted to do something `n` times... And I was used to do it this way from Go. And it was working :-)

**Comment by sejvlond** [comment]
Note: In PHP there is `@` operator for suppressing warnings/errors, http://php.net/manual/en/language.operators.errorcontrol.php but it's used as
`@encrypt(xxx)`
and it suppresses all error messages, I don't think, we should do the same.

Idea:
At the moment unused argument of a function is silently ignored:
`qore -nWe 'sub foo(int i) {} foo(2);'`
maybe we can add the same warning here, and if the function wants to ignore it,it should explicitly flush it?
`qore -nWe 'sub foo(int i) { @ = i; } foo(2);`

Or maybe it's a silly idea.

**Comment by martin-zemek** [comment]
`@ = ` seems good to me (though I would prefer the operator ignore - there would not be compatibility threats unlike with the function ignore()).

As for `_`, I personally also use it sometimes as a variable name in cases where it stands for an unused variable, in particular when it is an unused function argument (you can see it for example in uk-038-inv_store_issue-sim-mtl_transactions_interface-in.qmapper: `string sub(any _, hash rec) {...}` - the argument `_` is not used there).

At this moment - also after discussion with Petr - I would actually vote for the solution not to implement anything and simply solve it by assigning the return value to a variable and delete the variable on the next line - such code clearly indicates what's going on. (We can also pick some fitting name in such situations like 'unused' or 'trash' to make it even clearer - I would use '_'). All this discussion is about rarely occurring code - it can only appear in the form of the above example - when we ONLY TEST whether a function call would throw an exception.

What about making it a best practice/coding standard to use '_' for unused variables?

**Comment by sejvlond** [comment]
> What about making it a best practice/coding standard to use '_' for unused variables?

yes, why not, problem is, that you can have only one `_` in the block of code, so things like `sub foo(auto _, auto _)`, or `auto _ = 1; auto _ = (34,2);` are not possible, which makes it limited (this is possible to do in Go, where `_` is reserved). I added it here
https://qoretechnologies.com/devs/tiki-index.php?page=Recommended+Naming+Conventions

> Note: for unused variable it is commonly used _ (e.g. int sub foo(int x, auto _) { return x + 1; }

**Comment by davidnich** [comment]
consensus: merge as is, fix affected code (warning) + can open another issue for `@` if necessary / justified

**Review by davidnich — APPROVED** [review]

**Review by sejvlond — APPROVED** [review]

**Pull request merged**
