### PR TITLE
Feature/QUnit_assertThrows

### PR DESCRIPTION
**Pull request by gamato**
Fix status printing of assertThrows methods.
Fix status printing of assertTrue and assertFalse methods.

### CODE REVIEW

**Comment by davidnich** [comment]
can you please remove the "= NOTHING" assignments?   I think this is bad style...

**Comment by gamato** [comment]
Do you mean in method signatures ? ... (They had been there already.)

**Comment by omusil24** [comment]
Yes. You can remove them since the *string type is used there...

**Comment by davidnich** [comment]
@gamato thank you!

**Pull request merged**
