### PR TITLE
get_schema.q: very preliminary version of a tool for extracting schema definitions from datasources

### PR DESCRIPTION
**Pull request by rklx**

### CODE REVIEW

**Comment by omusil24** [comment]
trigger_pull_request_build

**Comment by pvanek** [comment]
errors:

```
qore get_schema.q "oracle:pvanek_omq/omq@xbox(al32utf8)"
unhandled QORE System exception thrown in TID 1 at 2015-12-04 09:53:54.599827 Fri +01:00 (CET) at get_schema.q:38
RUNTIME-TYPE-ERROR: <lvalue> expects type 'list', but got no value instead

pvanek@spongebob:~/work> qore get_schema.q -t workflow "oracle:pvanek_omq/omq@xbox(al32utf8)"
unhandled QORE System exception thrown in TID 1 at 2015-12-04 09:54:33.919476 Fri +01:00 (CET) at get_schema.q:39
RUNTIME-TYPE-ERROR: <lvalue> expects type 'list', but got no value instead

pvanek@spongebob:~/work> qore get_schema.q -t workflows -s foo "oracle:pvanek_omq/omq@xbox(al32utf8)"
unhandled QORE User exception thrown in TID 1 at 2015-12-04 09:57:29.580222 Fri +01:00 (CET) in create_table_string() (get_schema.q:208, user code)
COLUMN-TYPE-NOT-SUPPORTED: Please specify the list of allowed attributes for type varchar2
call stack:
  1: create_table_string() (get_schema.q:62, user code)
```

showstoppers (imho):
    - better help
    - full schema by default = all supported objects
    - table constraints, indexes, and triggers if is table specified
    - missing #!/usr/bin/env qore
    - make it executable

What about to rename get_schema.q to get_sql_schema.q?

later TODO:
    - views
    - materialized views
    - types
    - procedures
    - functions
    - packages

**Comment by rklx** [comment]
closing this pull request without removing the branch

**Comment by rklx** [comment]
thx @temnoregg:

kdyz si udelam schema z Oracle a pak to chci naloadovat na Postgres, tak je to rozbity, protoze to neumi konverzi number->numeric nebo neco takovyho mozna by to melo hodit jinej typ

to samy asi bude i s tim varchar2 -> varchar

 aha.. pisu do toho listu, diky

mozna to jsou nejaky specialny typy ve Schema ja nevim

a pak kdyz si to presmerujes do souboru a ten soubor se jmenuje jinak nez MySchema.qsm, tak to nejde naloadovat

takze jeste option pro to "module MySchema", ze si ho muzes nastavit

**Pull request closed without merging**
