### PR TITLE
Program::getAllDefines function, ParseOption2CodeMap&ParseOption2Stri…

### PR DESCRIPTION
**Pull request by tmandys**
I need it for debug branch. Please review.

### CODE REVIEW

**Review by davidnich — CHANGES_REQUESTED** [review]
please rename `ParseOption2CodeMap` to `ParseOptionToCodeMap` and `ParseOption2StringMap` to `ParseOptionToStringMap` to be consistent with other similar vars

**Comment by tmandys** [comment]
There are already _ParseOptionCodeMap_ and _ParseOptionStringMap_ working with _"PO_NEW_STYLE"_ form. I need _"new-style"_ to be consistent with qore command line format.

I did not find a valuable name, just "2". It is not substitution to "to". I'm happy when you get better name, maybe _ParseOptionCodeMap2_.

```
//! Maps from parse option code values (as string keys) to parse option names
/** @see ParseOptionStringMap for the reverse mapping

    @since %Qore 0.8.12
 */
const ParseOptionCodeMap = qore(pomaps.getCodeToStringMap());

//! Maps from parse option strings to parse option integer codes
/** @see ParseOptionCodeMap for the reverse mapping

    @since %Qore 0.8.12
 */
const ParseOptionStringMap = qore(pomaps.getStringToCodeMap());

//! Maps from parse option code values (as string keys) to parse option names. Names are in form used in script or on command line, e.g. new-style
/** @see ParseOption2StringMap for the reverse mapping

    @since %Qore 0.8.13
 */
const ParseOption2CodeMap = qore(ParseOptionMap::getCodeToStringMap());

//! Maps from parse option strings to parse option integer codes. Names are in form used in script or on command line, e.g. new-style.
/** @see ParseOption2CodeMap for the reverse mapping

    @since %Qore 0.8.13
 */
const ParseOption2StringMap = qore(ParseOptionMap::getStringToCodeMap());

```

**Comment by davidnich** [comment]
@tmandys ok I got it - what about `ParseOptionCmdStringMap` and `ParseOptionCmdCodeMap`?

**Comment by tmandys** [comment]
I also had an idea "*CmdLine*". The similar form is in code as "%new-style" which is not command. Anyway I'm not too strong in English naming. Tell what sounds good and I update it.  "*Cmd*" ?

**Comment by davidnich** [comment]
@tmandys `CmdLine` is also fine - as you like

**Comment by tmandys** [comment]
Done, *Cmd* is there,

**Review by davidnich — APPROVED** [review]

**Pull request merged**
