### PR TITLE
refs #1865 fixed bugs affecting debugging matching function/method va…

### PR DESCRIPTION
**Pull request by davidnich**
…riants and finding statements with special methods and with complex types

### CODE REVIEW

**Comment by tmandys** [comment]
Did you fix getting statement from inherited class? It should not be probably resolved as request is "_TestNS3::funcTest_" is fully qualified to _TestNS3_. It remains commented out in .qtest.

`assertThrows('PROGRAM-ERROR', \p.findFunctionVariants(), ("TestNS3::funcTest"), 'findFunctionVariants(TestNS3::funcTest)');  # TODO: resolved function from inherited class
`

**Comment by davidnich** [comment]
@tmandys no the behavior has not been changed here, basically when resolving symbols for debugging, methods are resolved like they are when you are programming in Qore, so if `ChildClass::baseMethod()` is actually only implemented in a parent/base class, then it will be resolved, however the search starts at the given class.  So from that point of view, it's logical.  Do you think it will be a problem to apply Qore's normal symbol resolution rules to such lookups?  Because there could be a case where a call like the above is made, but the method is actually implemented in a base class, so in such a case a programmer might try to look up the symbol as the call is written in the code, and if the debugger uses a different method of symbol resolution, the call will fail.

**Comment by tmandys** [comment]
@davidnich OK, I did not know that parent search is made in this case but what happens when the base class is implemented in C++ code, does it return nil ?

**Comment by davidnich** [comment]
> what happens when the base class is implemented in C++ code, does it return nil ?

the method search will return a value but then variant search will return `nullptr` because there is no user variant in such cases

**Pull request merged**
