### PR TITLE
Feature/restclient improvements

### PR DESCRIPTION
**Pull request by pvanek**

### CODE REVIEW

**Comment by pvanek** [comment]
@gamato @pavelkveton you can also review it, or merge ;)

**Comment by davidnich** [comment]
@pvanek can you please add release notes?  then assign to ondra for merging - with relnotes it's fine from my perspective

**Comment by pvanek** [comment]
module version bump too?

**Comment by davidnich** [comment]
@pvanek if it hasn't been updated since 0.8.12, then yes, otherwise no

**Comment by davidnich** [comment]
@pvanek can you please also add a release note in doxygen/lang/900_release_notes.dox.tmpl and reassign to @tethal for merging?

**Pull request merged**
