### PR TITLE
Additional CMake fixes

### LINKED ISSUE #1028: cmake marked as experimental
cmake output:

```
CMake Warning at CMakeLists.txt:668 (message):
  Please do not use cmake for production/real builds.  Cmake support is
  experimental and it does not contant all required setup
```

### PR DESCRIPTION
**Pull request by omusil24**
Let's make all the additional needed changes here...

> make install does not have docs in dependencies. Do we want something like "install-docs"? Or do we expect that docs are handled (rpm, deb) on the packager level?

@davidnich ?

fixes #1028

### CODE REVIEW

**Review by davidnich — APPROVED** [review]
re an `install-docs` target - we didn't have this in the autotools build, but it sounds like a good idea, as long as there is some standard target dir for it

**Comment by omusil24** [comment]
@davidnich is this version of the `install-docs` target fine?

**Comment by davidnich** [comment]
@omusil24 yes looks fine to me

**Comment by pvanek** [comment]
@omusil: please use cmake binary for multiplatform filesystem operations.

See:
https://cmake.org/cmake/help/v3.2/manual/cmake.1.html#command-line-tool-mode

Something like this will work in all systems (it needs to be tested for sure):

```
+add_custom_target(install-docs
    COMMAND ${CMAKE_COMMAND} -E make_directory ${CMAKE_INSTALL_PREFIX}/share/doc/qore
    COMMAND ${CMAKE_COMMAND} -E copy_directory ${CMAKE_BINARY_DIR}/docs/* ${CMAKE_INSTALL_PREFIX}/share/doc/qore
    COMMENT "Installing API documentation to: ${CMAKE_INSTALL_PREFIX}/share/doc/qore" VERBATIM
)
```

**Comment by omusil24** [comment]
@pvanek is there any other CMake issue that should be fixed?

If not, I think you can merge this.

**Review by pvanek — APPROVED** [review]

**Pull request merged**
