### PR TITLE
refs #417 fixed typos in SqlUtilTestBase

### PR DESCRIPTION
**Pull request by davidnich**
refs #408 added update tests to SqlUtilTestBase

### CODE REVIEW

**Comment by davidnich** [comment]
@omusil24 I cannot explain why this is failing either - everything has been updated - it succeeds in my environment - let's please look into this

**Comment by davidnich** [comment]
never mind - it was an environment problem on xbox - now everything's suddenly OK!

**Comment by omusil24** [comment]
@davidnich I was looking into it yesterday but didn't find anything. What was the cause? As it was failing on my computer (ren) too.

**Comment by omusil24** [comment]
Nevermind. I thought this was pull request #450, where the statement.qtest was failing but you said that it was because of a bug in the test.

**Pull request merged**
