### PR TITLE
refs #3012 fixed cmake builds on debian/ubuntu - must use arch-specif…

### PR DESCRIPTION
**Pull request by davidnich**
…ic dirs to install libs / modules

### CODE REVIEW

**Review by pvanek — COMMENTED** [review]
should not we use GNU install dirs instead?
It should solve this issue out of the box for us:

LIBDIR
    object code libraries (`lib` or `lib64` or `lib/<multiarch-tuple>` on Debian)

https://cmake.org/cmake/help/v3.4/module/GNUInstallDirs.html

**Comment by davidnich** [comment]
@pvanek gnu install dirs are used, but the cmake module does not set the library directory properly on debian/ubuntu systems for x86_64, it uses for example `/usr/local/lib` instead of `/usr/local/lib/x86_64-linux-gnu` - so cmake would install both 32-bit and 64-bit libraries to the same directory with the same name.  The autotools build sets this correctly (AFAIK it's correct that is) to the arch-specific directory on debian/ubuntu.   cmake works properly on non-debian/ubuntu systems regarding arch-specific dirs - setting for example `/usr/local/lib64` on all other Linuxes I've tested

**Comment by omusil24** [comment]
I would add a check that the current setting is really without the architecture suffix before adding it so that in case it works as it should, this fix won't generate something like `/usr/lib/x86_64-linux-gnu/x86_64-linux-gnu`.

**Comment by davidnich** [comment]
@omusil24 you were right; GNUInstallDirs sets the variable when the prefix is `/usr` but not on other directories, even though it should according to the information I found at least - I fixed the cmake build & tested it

**Comment by davidnich** [comment]
so according to the following references, 64-bit libraries should be stored in `x86_64-linux-gnu` subdirectories, not just in `/usr` as cmake does, but for all library directories on Debian:
* https://wiki.debian.org/Multiarch/TheCaseForMultiarch
* https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=685519

Also for example `/usr/local/lib/x86_64-linux-gnu` was added to the default system library path as per the second link.  cmake however will install both 32-bit and 64-bit libraries in the same directory if the target prefix is not `/usr`

**Pull request merged**
