### PR TITLE
Bugfix/1976 trans op fix

### PR DESCRIPTION
**Pull request by davidnich**

### CODE REVIEW

**Comment by omusil24** [comment]
I think there's a bit of a problem now. In case there was a parse error after both `REGEX_TRANS_BEGIN` and `REGEX_TRANS` were scanned, they would both be released and therefore the memory would be deleted twice leading to segfault or something like that, no?

**Review by pvanek — COMMENTED** [review]
Just a Q: should not be updated astparser's ypp too?

**Comment by davidnich** [comment]
@omusil24 you might be right, I suppose we need a new solution - let me check that

**Comment by davidnich** [comment]
@omusil24 I don't think this is a problem because `REGEX_TRANS_BEGIN` will only be destroyed if there is no `REGEX_TRANS` token, otherwise it's parsed with `REGEX_TRANS` and then the `REGEX_TRANS` is destroyed.

The same goes for other affected tokens (string + all other regex tokens).

I fixed the bug generally for all cases and added tests.

**Review by omusil24 — APPROVED** [review]

**Pull request merged**
