### PR TITLE
Added StdoutOutputStream and StderrOutputStream classes.

### PR DESCRIPTION
**Pull request by omusil24**

### CODE REVIEW

**Comment by davidnich** [comment]
@omusil24 I would like to discuss how these should work in respect to `PO_NO_TERMINAL_IO` (https://docs.qore.org/current/lang/html/parse_directives.html#no-terminal-io) - for example we check for this restriction at runtime with the old `stdin`, `stdout`, and `stderr` constants, but with streams I believe that this restriction is not currently enforced.   Let's please discuss that before merging this.

**Comment by davidnich** [comment]
@omusil24 can you please add a link in the relnotes?  the new stream classes are listed there

**Comment by omusil24** [comment]
Add link where? The classes are mentioned in the 900_release_notes.dox.tmpl in the "New Features in Qore" part of Qore 0.8.13.

**Comment by davidnich** [comment]
@omusil24 ok thanks, I missed that somehow

**Pull request merged**
