### PR TITLE
refs #1025 fixed reference counting and copy-on-write violation bugs …

### PR DESCRIPTION
**Pull request by davidnich**
…in the implementation of lazy evaluation for functional operators

### CODE REVIEW

**Comment by pavelkveton** [comment]
let's at least wait for the qorus test whether it is fixed. If the bug is as we expect, then the following code should have been crashing too (or at least valgrind should have a word to it), I believe:

`./qore -e 'my hash $h = ("a" : NULL, "b" : 1, "c" : NULL); map delete $h.$1, keys $h, $h.$1 === NULL;'`

but valgrind is happy with it.

BTW: is the function QoreValue::isTemp() necessary. I see it appearing only in the code that is deleted by the last commit...

**Comment by davidnich** [comment]
@pavelkveton I added a test for the fix now

**Comment by davidnich** [comment]
> BTW: is the function QoreValue::isTemp() necessary. I see it appearing only in the code that is deleted by the last commit...

`ValueOptionalRefHolder::isTemp()` is still used in various places...

**Comment by pavelkveton** [comment]
ok, I feel convinced by the added test - it crashes to me to before the fix.

**Pull request merged**
