### PR TITLE
clang-format

### PR DESCRIPTION
**Pull request by petrycta**
This pull request created just as example. Please have a look, commit or write down as comments your suggestions to improve. Thanks

### CODE REVIEW

**Comment by turlyalz** [comment]
Clang-format also supports reordering include groups. Please see **IncludeCategories** option. IMHO It would be good to have it in this order (from more specific to less specific):

1. Some specific stuff like including Qore headers
2. 3rd-party libraries or std libs
3. System includes.

**Comment by sejvlond** [comment]
@turlyalz there are [huge discussions](https://stackoverflow.com/questions/2762568/c-c-include-file-order-best-practices) about the order :)  
for example [google c++ style guide](https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes) says it the opposite, but the one that is always the same and that makes sense is:

> 1, the header for the cpp file, like `dir2/foo2.h.`
> With the preferred ordering, if dir2/foo2.h omits any necessary includes, the build of dir/foo.cc or dir/foo_test.cc will break. Thus, this rule ensures that build breaks show up first for the people working on these files, not for innocent people in other packages.

then I don't care, but let's choose one and let's use it (automatically formatted with clang for sure), 

also

> Within each section the includes should be ordered alphabetically.

and use forward declarations whenever possible

**Comment by geckon** [comment]
I think that the Google style guide's order makes more sense but maybe that's just me ;)

**Comment by turlyalz** [comment]
@sejvlond OK, we can use google c++ style guide for including order. :)

That means:
1. dir2/foo2.h.
2. A blank line
3. C system files.
4. C++ system files.
5. A blank line
6. Other libraries' .h files.
7. Your project's .h files.

**Comment by omusil24** [comment]
+1 for the Google style. I use that one everywhere. Also a blank line between the other libraries and my project's headers.

Also, one important thing - don't use C includes directly. Always use the wrapped C++ version. That is, instead of `math.h` use `cmath`, instead of `stdlib.h` use `cstdlib` etc. Using the C includes directly can sometimes mess up some symbol definitions.

**Comment by omusil24** [comment]
Regarding the settings, one thing I don't like is the indented include directive in the `#ifdef` block:
```
#ifdef HAVE_GLOB_H
#    include <glob.h>
#else
#    include "qore/intern/glob.h"
#endif
```
That just looks wrong.

Also the following looks weird:
```
static void qore_check_load_module_intern(
    QoreAbstractModule* mi, mod_op_e op, version_list_t* version, QoreProgram* pgm, ExceptionSink& xsink) {
```
IMO either everything should be on the same line, or on the next line like this but then each variable should be on new line:
```
static void qore_check_load_module_intern(
    QoreAbstractModule* mi,
    mod_op_e op,
    version_list_t* version,
    QoreProgram* pgm,
    ExceptionSink& xsink) {
```

**Comment by davidnich** [comment]
I like the idea of having a single automated style that's applied to all our code - it will make merging changes from earlier branch more difficult however.

I don't care that much about what it looks like if the style is applied automatically and everyone else can agree on a certain style

**Review by pvanek — APPROVED** [review]

**Review by davidnich — APPROVED** [review]

**Comment by pvanek** [comment]
also there comes a some static analysis tools with clang. Here is a sample:
https://hq.qoretechnologies.com/~pvanek/scan-build-2018-09-19-162612-21438-1/
No idea how much is it relevant

**Comment by omusil24** [comment]
I'm going to go through all the settings and fix the issues I mentioned and hopefully even others that might have gone unnoticed. So don't merge please.

**Pull request closed without merging**
