### PR TITLE
Bugfix/1791 this nullptr crashes

### PR DESCRIPTION
**Pull request by omusil24**
Checking commit by commit might be easier than checking it all at the same time.
refs #1791

### CODE REVIEW

**Review by davidnich — APPROVED** [review]
massive effort - great job - everything looks good from my point of view

**Comment by pvanek** [comment]
I am speechless. I suggest to merge it, then I will rebuild all packages so it can show real impact.

**Comment by omusil24** [comment]
I'm not totally sure about that ExceptionSink usage though. I think I will run Qorus+tests with this version to make sure it works fine.

**Comment by davidnich** [comment]
@omusil24 please go ahead and try but I have done that and everything is working fine

**Comment by omusil24** [comment]
Ok, then you can merge it...
And after it's merged, I will make a pull request for develop and fix the conflicts...

**Pull request merged**
