### PR TITLE
Feature/mapper runtime opts

### PR DESCRIPTION
**Pull request by pvanek**
please review. Main questions are:
- is it a good approach?
- should it throw an exception if user tries to access non-existing runtime key/value (TODO/FIXME in diff below)

### CODE REVIEW

**Comment by davidnich** [comment]
I added release notes and some doc corrections and added some more helper methods, etc - however I just realized that there was some existing functionality that would possibly cover this use case equally well: Mapper::addConstantMapping(hash)

Can you please check that out and see if we need runtime options?  Maybe the existing constant mapping functionality covers the need for runtime options.  Sorry I did not remember this before when we first discussed this.

**Comment by davidnich** [comment]
also BTW I found that tagging Qore code examples as python makes the examples render better with doxygen - ex: @code{.py} ... @endcode

**Comment by pvanek** [comment]
perfect. addConstantMapping(hash) is exactly what I need. I also added addConstantMapping(string key, any value) as a shortcut for single key/value setting

**Comment by davidnich** [comment]
ok so should the runtime option support be removed from the Mapper class or do you want to leave it in?

It seems redundant if you want to use addConstantMapping()...

**Comment by pvanek** [comment]
it's gone. If you look at the final diff: https://github.com/qorelanguage/qore/pull/199/files
you can see only minimal changes (but I still believe that they are useful changes at all)

**Pull request merged**
