### PR TITLE
Make the backtrace check in cmake work.

### PR DESCRIPTION
**Pull request by niclasr**
FindBacktrace might set its variables even if it does not find backtrace.
Due to this we only want to add its include dirs and libraries to libqore
if it is found.

### CODE REVIEW

**Comment by niclasr** [comment]
I added davidnich to the reviewers so he can test if this fixes #1026 .

**Review by davidnich — APPROVED** [review]
looks good

**Comment by davidnich** [comment]
however #1026 is not fixed - when building with g++ 5.2.0 I get:
```
In file included from /export/home/dnichols/src/sparc/qore/git/qore/include/qore/intern/config.h:41:0,
                 from /export/home/dnichols/src/sparc/qore/git/qore/include/qore/Qore.h:42,
                 from /export/home/dnichols/src/sparc/qore/git/qore/build/QC_AutoReadLock.cpp:32:
/export/home/dnichols/src/sparc/qore/git/qore/include/qore/intern/unix-config.h:17:29: error: 'tr1' in namespace 'std' does not name a type
 #define HASH_NAMESPACE std::tr1
``

**Review by omusil24 — APPROVED** [review]

**Comment by omusil24** [comment]
@davidnich that is a separate issue I believe.
Can you please try deleting that `unix-config.h` file? The autotools one and CMake clash when both are present.

**Comment by davidnich** [comment]
@omusil24 yes, it's a separate issue, please go ahead and merge this, and if there's a problem with the cmake build after I try your suggestion, then I'll open a separate issue.  I don't want to turn on the sparc machine during the day, because it's so loud...

**Pull request merged**
