### PR TITLE
MailMessage.qm: Fixed broken constructor for attachments + unittest

### PR DESCRIPTION
**Pull request by pvanek**

### CODE REVIEW

**Comment by omusil24** [comment]
The branch is wrongly named. It should be bugfix/xxxx. hotfix/xxxx is for fixes in the old (0.8.11.1) branch.

**Comment by pvanek** [comment]
even if it's in unreleased code?

**Comment by davidnich** [comment]
@omusil24 can you please fix? Please merge when done, the fixes are fine

**Comment by omusil24** [comment]
@pvanek @davidnich It doesn't matter if it's unreleased or released. Hotfix is for old branch, bugfix is for develop. Jenkins is set up with that in mind. That's why the tests failed.

**Pull request closed without merging**
