### PR TITLE
refs #1250 ported the lost connection API to 0.8.12; added the Dataso…

### PR DESCRIPTION
**Pull request by davidnich**
…urce::connectionLost() API to allow drivers to ensure that all open statements are closed when a connection is lost to allow drivers such as oracle to close all handles on the current connection object

### CODE REVIEW

**Comment by davidnich** [comment]
@omusil24 do not merge yet

**Comment by davidnich** [comment]
@omusil24 now it is OK

**Comment by omusil24** [comment]
IMO @pavelkveton should check this before merging.

**Review by omusil24 — APPROVED** [review]

**Comment by davidnich** [comment]
@omusil24 then please assign Pavel

Note that the Oracle driver change is more intrusive and is the one that will need review and discussion

**Review by pavelkveton — APPROVED** [review]
I understand that this is critical issue that needs to be fixed in 0.8.12. It would take long time for me to understand how it is fixed, though.

The only thing I can say that `mutable` would not pass any review of mine. But since I don't know what this is about, I have to trust the implementation...

**Comment by pavelkveton** [comment]
assigning back to David to merge - I already put my approval there...

**Comment by davidnich** [comment]
@pavelkveton email sent to discuss & clarify `mutable` issues out of band

**Pull request merged**
