### PR TITLE
SchemaReverse: implementation

### PR DESCRIPTION
**Pull request by pvanek**
@davidnich all your notes are aligned in this new implementation (most parts are already part of qore, done in previous PR)

### CODE REVIEW

**Comment by pvanek** [comment]
@omusil24 our jenkins does not accept forked repos PR?

**Comment by omusil24** [comment]
@pvanek not right now

**Comment by pvanek** [comment]
@omusil24  good to know for next time. Can you merge this one without it, please? Or should I do it again with regular branch?

**Comment by omusil24** [comment]
trigger_pull_request_build

**Comment by tethal** [comment]
test

**Comment by omusil24** [comment]
@pvanek Yes, push the branch to the qorelanguage/qore repo please.

**Pull request closed without merging**
