### PR TITLE
Feature/2966 split module docs

### PR DESCRIPTION
**Pull request by petrycta**

### CODE REVIEW

**Review by davidnich — APPROVED** [review]
looks good to me!

**Comment by sejvlond** [comment]
git blame works fine, content of the split files blames the original authors since 2012,
git log on the other hand shows history only since 2018 where you split the module into multiple files, but I guess this is not possible to do differently

So I'm fine with it, can you please update the branch (ideally rebase it on develop)?

**Comment by petrycta** [comment]
@sejvlond done

**Comment by petrycta** [comment]
@sejvlond well, no its not. ConnectionProvider.qm was  reconstructed and it should splitted again

**Comment by sejvlond** [comment]
it's out-of-date again (sorry, let's talk tmrw and plan when to update it and merge it), also one build doesn't succeeded

**Comment by petrycta** [comment]
> it's out-of-date again (sorry, let's talk tmrw and plan when to update it and merge it), also one build doesn't succeeded

of course, see my comment above

**Comment by davidnich** [comment]
docs look good - aligned with develop - from my point of view OK to merge

**Pull request merged**
