### PR TITLE
Feature/1049 util fix

### PR DESCRIPTION
**Pull request by davidnich**

### CODE REVIEW

**Comment by tethal** [comment]
shouldn't this be merged to 0.8.12 instead of develop?

**Comment by davidnich** [comment]
yes -sorry I made a mistake - can we merge it first here and then in 0.8.12, or does it need to be the other way around

**Comment by tethal** [comment]
no problem, I just wanted to make sure I understand it. I merged it to both 0.8.12 and develop, so it should be ok now.

**Comment by davidnich** [comment]
@tethal thank you!

**Pull request merged**
