### PR TITLE
Bugfix/423 deterministic gc closure scans

### PR DESCRIPTION
**Pull request by davidnich**

### CODE REVIEW

**Comment by tethal** [comment]
This needs to be tested thoroughly before merging.

**Comment by omusil24** [comment]
The leaks are still there: https://gist.github.com/omusil24/c72599cee5c7a95d5983

Here's the list of the leaking tests: bare-ref-test.qtest, mapper.qtest, SqlStatementMapperIterator.qtest, SqlStatementOutboundMapper.qtest, FreetdsSqlUtil.qtest, OracleSqlUtil.qtest, PgsqlSqlUtil.qtest, gc.qtest, members.qtest, program.qtest, parse_directives.txt

**Comment by davidnich** [comment]
I'll check this later on Linux - at least with members.qtest as tested on OSX there are no more leaks - are you sure you're testing against this branch?

**Comment by omusil24** [comment]
@davidnich Yes, I'm sure. By the way, I don't think it's possible to do a nice view of the valgrind output in Jenkins. I tried to use Valgrind plugin in Jenkins but the Valgrind output for all the tests is just too big so Jenkins fails when trying to view the results. (Oh, actually now the whole Jenkins is failing.)

However, I'm saving all the valgrind output to this directory on xbox: /var/lib/jenkins/workspace/qore_valgrind_output/qv_$BUILD_NUMBER
There's a text file with the output for each test. And when running the actual build on Jenkins, there's a list of the tests with "definite leaks" printed at the end so you know which tests to check.

**Comment by davidnich** [comment]
@omusil24 here are my results from running members.qtest under valgrind on Linux for branch bugfix/423_deterministic_gc_closure_scans:

```
==29874== LEAK SUMMARY:
==29874==    definitely lost: 0 bytes in 0 blocks
==29874==    indirectly lost: 0 bytes in 0 blocks
==29874==      possibly lost: 48 bytes in 2 blocks
==29874==    still reachable: 5,608 bytes in 17 blocks
==29874==         suppressed: 0 bytes in 0 blocks
```

so from my point of view, at least with members.qtest (leaving out the overall correctness of the fixes in this branch - which is a more complex issue) - the memory leak at least in this test script has been fixed.

So I would like to ask you to please verify this by hand to ensure that your vangrind run with this branch is not actually using a system-provided libqore (for example) and therefore not actually testing the libqore built by this branch.

**Comment by davidnich** [comment]
valgrind with members.qtest again after today's optimization commits:

```
==22904== LEAK SUMMARY:
==22904==    definitely lost: 0 bytes in 0 blocks
==22904==    indirectly lost: 0 bytes in 0 blocks
==22904==      possibly lost: 48 bytes in 2 blocks
==22904==    still reachable: 5,608 bytes in 17 blocks
==22904==         suppressed: 0 bytes in 0 blocks
```

I also checked a couple of others (bare-refs-test.qtest and PgsqlSqlUtil.qtest) and get 0 bytes definitely lost, but those show lots of possibly lost memory, which appears to be related to circular references with Program object - so most likely another issue

**Comment by omusil24** [comment]
@davidnich Just checked it and the members.qtest and gc.qtest don't have the definite leaks anymore. The other tests are still failing. At least these 4 with definite leaks: bare-refs-test.qtest, mapper.qtest, parse_directives.qtest, program.qtest.
I didn't test all the other ones except Freetds and the SqlOutboundMapper test and those two don't have definite leaks but still have lots of 'still reachable' and 'possibly lost' leaks. @tethal has a little bit different results

By the way I'm testing it like this:
`LD_LIBRARY_PATH=./lib/.libs:$LD_LIBRARY_PATH valgrind --run-libc-freeres=yes --tool=memcheck --num-callers=50 --leak-check=yes --show-reachable=yes ./.libs/qore test/qore/vars/members.qtest >valgrind_out.txt 2>&1`

**Comment by tethal** [comment]
My results are as follows:

```
./examples/test/qore/misc/parse_directives.qtest
==18867==    definitely lost: 152 bytes in 2 blocks

./examples/test/qore/classes/Program/program.qtest
==18962==    definitely lost: 64 bytes in 1 blocks

./examples/test/qore/vars/bare-ref-test.qtest
==19698==    definitely lost: 24 bytes in 1 blocks

./examples/test/qlib/SqlUtil/OracleSqlUtil.qtest
==19883==    definitely lost: 49 bytes in 1 blocks

./examples/test/qlib/Mapper/mapper.qtest
==19939==    definitely lost: 24 bytes in 1 blocks

./examples/test/qlib/TableMapper/SqlStatementMapperIterator.qtest
==20021==    definitely lost: 24 bytes in 1 blocks

./examples/test/qlib/TableMapper/SqlStatementOutboundMapper.qtest
==20024==    definitely lost: 24 bytes in 1 blocks
```

I can confirm that members.qtest on develop branch leaked for me as well, so at least this seems to be fixed.

**Comment by tethal** [comment]
We managed to eliminate everything from the mapper.qtest not related to the memory leak and this is what is left:

```
#!/usr/bin/env qore
# -*- mode: qore; indent-tabs-mode: nil -*-

%require-types
%enable-all-warnings
%new-style
%strict-args

const x = sub() {};

sub f() {
    print(x);
}

==21471==    definitely lost: 24 bytes in 1 blocks
```

which seems identical to #44

**Comment by tethal** [comment]
There seems to be a leak when the parser encounters an error - it probably does not deallocate the AST nodes which get thrown away. This is not likely to be an issue in Qorus production, but it is probably the cause of some of the leaks in our tests, because we do test that the parser throws an exception under certain circumstances. I will have a look at the parser later, for now I'll try to analyze  the remaining issues in qtests to see if they are all related to either this or #44 or if there is something else...

```
otethal@quack:~/src/qore/git/qore$ valgrind qore -e m
==21681== Memcheck, a memory error detector
==21681== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
==21681== Using Valgrind-3.10.1 and LibVEX; rerun with -h for copyright info
==21681== Command: qore -e m
==21681== 
unhandled QORE System exception thrown in TID 1 at 2016-01-20 11:54:09.736596 Wed +01:00 (CET) at <command-line>:1
PARSE-EXCEPTION: syntax error, unexpected $end
==21681== 
==21681== HEAP SUMMARY:
==21681==     in use at exit: 73,786 bytes in 10 blocks
==21681==   total heap usage: 54,208 allocs, 54,198 frees, 2,706,483 bytes allocated
==21681== 
==21681== LEAK SUMMARY:
==21681==    definitely lost: 64 bytes in 1 blocks
==21681==    indirectly lost: 2 bytes in 1 blocks
==21681==      possibly lost: 24 bytes in 1 blocks
==21681==    still reachable: 73,696 bytes in 7 blocks
==21681==         suppressed: 0 bytes in 0 blocks
==21681== Rerun with --leak-check=full to see details of leaked memory
==21681== 
==21681== For counts of detected and suppressed errors, rerun with: -v
==21681== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

**Comment by tethal** [comment]
So the leaks in parse_directives.qtest and program.qtest are related to parse exceptions, and the following are instances of #44:
    bare-ref-test.qtest
    Mapper/mapper.qtest
    SqlStatementMapperIterator.qtest
    SqlStatementOutboundMapper.qtest

The only remaining leaking test on my machine is OracleSqlUtil.qtest, but I don't know if the Valgrind report isn't misleading, since it generates tons of weird errors. On the other hand, having a memory leak in Oracle-related code would be terrible, so it is probably worth investigating more.

**Comment by tethal** [comment]
I've created #425 for the leaks related to parse-exception and since the others are related to #44 and the leak in OracleSqlUtil.qtest are on develop as well (i.e. not introduced by this fix), I think we may consider this issue #423 fixed and merge this PR to develop.

**Comment by davidnich** [comment]
Ok @tethal please merge if you're happy with it now. Note that there are still actions to be done regarding covering recursive loops in closure-bound local vars,but we can discuss that in our meeting later.

**Comment by davidnich** [comment]
@omusil24 jenkins is marking the build as failed because gc.qtest is failing there, but it does not fail for me with a build from this branch.  I just started a manual rebuild, but it also failed - can you please take a look?

**Comment by davidnich** [comment]
@omusil24 I've re-assigned to me because I'm working on the complete solution for handling recursive references in closure-bound local variables as well; this will take longer.  But it still looks like the Jenkins builds have a problem somewhere...

**Comment by omusil24** [comment]
@davidnich It's caused by wrong library paths. Even though I run the tests with LD_LIBRARY_PATH set to "./lib/.libs:./qlib:LD_LIBRARY_PATH", the libs seem to be taken from the standard /usr paths. Trying to find a solution now.

**Comment by davidnich** [comment]
just committed massive changes that treat closure-bound lvars at the same level as objects - the rsection code was abstracted and qore_object_private and ClosureVarValue both inherit RObject which is where all the common processing is performed.

I added one simple test with closures to gc.qtest as per the above example that was failing.  It needs more testing, but it's going in the right direction.

@tethal please review

**Comment by tethal** [comment]
:+1:
Now @omusil24 needs to fix Jenkins setup and then we can check that the only definite leaks reported by Valgrind are these:

```
./examples/test/qore/vars/bare-ref-test.qtest
==19698==    definitely lost: 24 bytes in 1 blocks

./examples/test/qlib/Mapper/mapper.qtest
==19939==    definitely lost: 24 bytes in 1 blocks

./examples/test/qlib/TableMapper/SqlStatementMapperIterator.qtest
==20021==    definitely lost: 24 bytes in 1 blocks

./examples/test/qlib/TableMapper/SqlStatementOutboundMapper.qtest
==20024==    definitely lost: 24 bytes in 1 blocks

./examples/test/qlib/SqlUtil/OracleSqlUtil.qtest
==19883==    definitely lost: ca; tens of bytes in 1 blocks
```

**Comment by davidnich** [comment]
@omusil24 I forgot about "qore"; if you are using autotools to build qore, then "qore" is a shell script created in the root source directory that will ensure that the library from the build is used instead of any system libraries.  You should use that to run the tests in run_tests.sh

**Pull request merged**
