### PR TITLE
cmake build: fixed unused linking against Thread::Thread

### PR DESCRIPTION
**Pull request by pvanek**
@niclasr please review too

With current cmake build I'm facing many error messages like this:

```
-- Looking for bzero
CMake Error at CMakeLists.txt:11 (add_executable):
  Target "cmTryCompileExec3965296457" links to target "Threads::Threads" but
  the target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?


CMake Error: Internal CMake error, TryCompile generation of cmake failed
-- Looking for bzero - not found
```

All compiles fine when I remove Threads::Threads string from the libs. But I really have no clue what it was for.

lib/interpreters are linked against pthreads out of the box without it

```
pvanek@spongebob:~/src/qore/qore/build> ldd ./qore
        linux-vdso.so.1 (0x00007fffe8da9000)
        libqore.so => /export/home/pvanek/src/qore/qore/build/libqore.so (0x00007fdf7d3e5000)
        libbz2.so.1 => /usr/lib64/libbz2.so.1 (0x00007fdf7d1a9000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007fdf7cfa5000)
        libmpfr.so.4 => /usr/lib64/libmpfr.so.4 (0x00007fdf7cd4a000)
        libssl.so.1.0.0 => /lib64/libssl.so.1.0.0 (0x00007fdf7cae2000)
        libcrypto.so.1.0.0 => /lib64/libcrypto.so.1.0.0 (0x00007fdf7c6bf000)
        libpcre.so.1 => /usr/lib64/libpcre.so.1 (0x00007fdf7c453000)
        libz.so.1 => /lib64/libz.so.1 (0x00007fdf7c23c000)
        libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007fdf7bf34000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fdf7bc33000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fdf7ba1b000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fdf7b674000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fdf7d99c000)
        libgmp.so.10 => /usr/lib64/libgmp.so.10 (0x00007fdf7b3ed000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fdf7b1cf000)
```

### CODE REVIEW

**Comment by niclasr** [comment]
The reason THeads:Threads is needed is that pthread_attr_getstacksize that qore_check_funcs looks for  is in libpthread. If you run without Threads:Threads, is it found on your system? It's not found on mine without Threads:Threads.

**Comment by niclasr** [comment]
You can try to use ${CMAKE_THREAD_LIBS_INIT} instead of Threads:Threads in CMAKE_REQUIRED_LIBS to see if that works. it works for me.

**Comment by niclasr** [comment]
Without Threads::Threads in target_link_libraries I get
CMakeFiles/qore.dir/qore-single-compilation-unit.cpp.o:(.rodata+0x1e80): undefined reference to `pthread_cancel'
libqore.so: undefined reference to`pthread_create'
libqore.so: undefined reference to `pthread_attr_getstacksize'
libqore.so: undefined reference to`pthread__cleanup_push'
libqore.so: undefined reference to `pthread_attr_init'
libqore.so: undefined reference to`pthread_attr_setdetachstate'
libqore.so: undefined reference to `pthread_kill'
libqore.so: undefined reference to`pthread_testcancel'
libqore.so: undefined reference to `pthread__cleanup_pop'
libqore.so: undefined reference to`pthread_detach'
libqore.so: undefined reference to `pthread_attr_destroy'
**\* Error code 1
on NetBSD.

**Comment by pvanek** [comment]
@niclasr thanks, it works here

**Comment by tethal** [comment]
Looks good to me. @niclasr, is it ok to merge? Thx.

**Comment by niclasr** [comment]
Sure, just merge.

**Pull request merged**
