### PR TITLE
refs #2936 improve mime module

### PR DESCRIPTION
**Pull request by petrytar**

### CODE REVIEW

**Review by davidnich — CHANGES_REQUESTED** [review]
please add a test for this - in general with such things we should do TDD (i.e. test first, fix second)

**Comment by petrytar** [comment]
Ok

**Comment by petrytar** [comment]
so, as far as I have analyzed, any string (with or without binary data) that has been received from the socket by Mime:: parseBody method, can be parsed from the end and closing boundary could be found. But when I was trying to create such a string with some text|binary_data|text function "rfind" function fails depending on binary data I send. I tried to open file with different encoding (e.g. ISO-8859-1 - the encoding we received from the socket), but it doesn't help.
Postponed till rebus task has been finished

**Comment by sejvlond** [comment]
@petrytar what's the state of this pull req? should we close it, or shall we work on it?

**Comment by petrytar** [comment]
We should merge it. The changes are trivial and can not provoke any bugs. It might not resolve all the issues related to binary files sent through rest, but it definitely fixed this one and it brings little efficiency when we do search in a right way (e.g. search closing boundary from the end).

**Comment by petrycta** [comment]
@davidnich @sejvlond We should merge it. The changes are trivial and can not provoke any bugs. It might not resolve all the issues related to binary files sent through rest, but it definitely fixed this one and it brings little efficiency when we do search in a right way (e.g. search closing boundary from the end).

**Comment by sejvlond** [comment]
ok, makes sense, just please write some test for it

**Comment by petrycta** [comment]
it does not broke existed tests, but I can not add another one. It only works for "binary requests" send outside from qorus ... I couldnt simulate this case in unittest

**Comment by davidnich** [comment]
@petrytar I wrote a test by inserting a binary `\0` in the existing test, and the test failed.  I think we need to use pure binary operations on the data instead of string operations, as string operations anyway are sensitive to the string's character encoding and always work on character boundaries.

However Qore is missing binary search functions - I opened another issue for this: #3300 

I would like to postpone this fix to 0.9.1 and do it properly with binary parsing of the MIME message bodies.

**Comment by petrytar** [comment]
> @petrytar I wrote a test by inserting a binary `\0` in the existing test, and the test failed. I think we need to use pure binary operations on the data instead of string operations, as string operations anyway are sensitive to the string's character encoding and always work on character boundaries.
> 
> However Qore is missing binary search functions - I opened another issue for this: #3300
> 
> I would like to postpone this fix to 0.9.1 and do it properly with binary parsing of the MIME message bodies.

could you please try your test in develop branch? This fix makes sens even if it not fix binary problem. All it does is look for a closing body boundary from the end

**Comment by davidnich** [comment]
@petrytar I tested it and it failed with develop - if your fix makes it better though anyway, then we can merge it, so you can reopen this merge request and assign to me if you want

**Pull request closed without merging**
